package com.drkiet.ireader.main;

public interface ReaderListener {
	public enum Command {
		START, STOP, RESET, RESTART, LOAD, LOAD_REF, START_AT, SMALLER_TEXT_FONT, LARGER_TEXT_FONT, PREVIOUS_PAGE,
		NEXT_PAGE, SMALLER_WORD_FONT, LARGER_WORD_FONT, HELP_PICTURE, BROWSE,  GOTO, NEXT_FIND, PREVIOUS_FIND,
		SELECT_TRANSLATION, PREVIOUS_EXACT_MATCH, NEXT_EXACT_MATCH,
		
		
		GOTO_PAGE,
		SEARCH, SEARCH_NEXT,
		SELECT_BOOK, OPEN_SELECTED_BOOK,
		SELECT_REFERENCE, OPEN_SELECTED_REFERENCE
	};

	void invoke(Command cmd);
}
